# -*- coding: utf-8 -*-
"""task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGenykTn6sQ674pUjLXEb_4f0KMUDnSB
"""
file= open('/content/input3a.txt','r')
out= open('output3.txt','w')
lines= file.readlines()
n= int(lines[0])
arr= [None]*n
for i in range(1,len(lines)):
  x= lines[i].strip().split(' ')
  a,b =x
  arr[i-1]=(int(a),int(b))

def schedule(arr, n):
    finarr = []
    arr.sort(key=lambda x: x[1]) 
    i = 0
    finarr.append(arr[i]) 
    for j in range(1, n):
        if arr[j][0] >= arr[i][1]:
            finarr.append(arr[j])
            i = j
    return finarr
  
finarr = schedule(arr, n)
print(len(finarr),file=out)
for i in finarr:
  x,y = i
  print(x, y,file=out)

file.close()