# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ah_vMxU7jJRWt7OB2nttYoNVWgINHdJR
"""


file = open('/content/input2a.txt','r')
out = open("output2.txt",'w')
f = file.readlines()
n= int(f[0])
f= f[1].split(' ')
for i in range(n):
  x= f[i].strip('\n')
  f[i]= int(x)

c=0
for i in range(0,n-1):
  for j in range(0,n-i-1):
    if int(f[j]) > int(f[j+1]):
      f[j],f[j+1] = (f[j+1]), (f[j])
      c=+1
  if c==0:
    break

print(f,file=out)
out.close()