# -*- coding: utf-8 -*-
"""task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSOtAjXkhV5R50ma-XwKcUgeBg4thR84#scrollTo=9hnbXr8UzGAp&uniqifier=3
"""
f = open('/content/input2a.txt','r')
out= open('output2.txt','w')
lines= f.readlines()
n= int(lines[0])
arr= lines[1].split(' ')
for i in range(len(arr)):
  x=int(arr[i])
  arr[i]=x

def findmax(arr):
  if len(arr)<=1:
    return arr[0]
  else:
    mid = len(arr)//2
    a1= findmax(arr[:mid])
    a2= findmax(arr[mid:])
    if a1>=a2:
      return a1
    else:
      return a2

print(findmax(arr))
print(findmax(arr),file=out)

out.close()