# -*- coding: utf-8 -*-
"""task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSOtAjXkhV5R50ma-XwKcUgeBg4thR84#scrollTo=9hnbXr8UzGAp&uniqifier=3
"""
f = open('/content/input3a.txt','r')
out= open('output3.txt','w')
lines= f.readlines()
n= int(lines[0])
arr= lines[1].split(' ')
for i in range(len(arr)):
  x=int(arr[i])
  arr[i]=x


def csmerge(arr, st, mid, end):
    scount = 0
    left = arr[st:mid+1]
    right = arr[mid+1:end+1]
    i,j=0,0
    k= st
    while i <len(left) and j <len(right):
      if left[i] <=right[j]:
        arr[k]= left[i]
        i+= 1
      else:
        arr[k]= right[j]
        j += 1
        scount+= (mid+1)-(st+i)
      k+= 1
    while i <len(left):
      arr[k]= left[i]
      i+= 1
      k+= 1
    while j <len(right):
      arr[k]= right[j]
      j+= 1
      k+= 1

    return scount

def countnswap(arr, st, end):
    if st >= end:
      return 0
    mid = st + (end - st) // 2
    scount = countnswap(arr, st, mid)
    scount += countnswap(arr, mid+1, end)
    scount += csmerge(arr, st, mid, end)
    return scount

res=countnswap(arr,0,n - 1)
print(res)
print(res,file=out)
out.close()