# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ziNProqnAzBslkKj-pgg57obnJydxCnT
"""
inp = open('/content/input3a.txt',mode='r')
out= open("output3.txt",'w')
lines= inp.readlines()
n=int(lines[0])

id= [None]*n
mark= [None]*n
x=(lines[1][0:-1]).split(" ")
y=(lines[2]).split(" ")

for i in range(n):
  id[i]=int(x[i])
  mark[i]=int(y[i])

c=0
for i in range(len(mark)-1):
  for j in range(len(mark)-i-1):
    if mark[j] > mark[j+1]:
      c+=1
      mark[j], mark[j+1] = mark[j+1], mark[j]
      id[j], id[j+1] = id[j+1], id[j]
    elif mark[j] == mark[j+1]:
      if id[j] < id[j+1]:
        mark[j], mark[j+1] = mark[j+1], mark[j]
        id[j], id[j+1] = id[j+1], id[j]
  if c==0:
    break


for i in range(n-1,-1,-1):
  print("ID: ",id[i],"Mark: ",mark[i],file=out)

out.close()