# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QzFgrRn5pt08_26Z1S_I_47AvZIFr2At
"""

inp = open('/content/input4.txt',mode='r')
out= open("output4.txt",'w')
lines= inp.readlines()
n=int(lines[0])
for i in range(n):
  lines[i]= lines[i][0:-1]

train = [None]*n
depart= [None]*n
time= [None]*n

for i in range(1,n+1):
  x= lines[i].split(" ")

  train[i-1] = x[0]
  depart[i-1]=x[4]
  time[i-1]=x[len(x)-1]

temp = train

def strval(stri):
  stri= stri.upper()
  sum = 0
  if len(stri)<5:
    for i in stri:
      sum+= ord(i)
  else:
    for i in range(5):
      s=6-i
      z= "1" + "0"*s
      sum+= ord(stri[i])*int(z)
  return sum


def timeval(str):
  val=0
  x= str.split(":")
  val += (int(x[0])*60) + int(x[1])
  return val

def sort3at1ce(train,time,depart):
  rc=0
  for i in range(len(train)-1):
    for j in range(len(train)-i-1):
      pre=strval(train[j])
      post=strval(train[j+1])
      if pre > post:
        rc+=1
        train[j], train[j+1] = train[j+1], train[j]
        time[j], time[j+1] = time[j+1], time[j]
        depart[j], depart[j+1] = depart[j+1], depart[j]
      elif strval(train[j]) == strval(train[j+1]):
        if timeval(time[j]) < timeval(time[j+1]):
          train[j], train[j+1] = train[j+1], train[j]
          time[j], time[j+1] = time[j+1], time[j]
          depart[j], depart[j+1] = depart[j+1], depart[j]
        elif timeval(time[j]) == timeval(time[j+1]):
          if temp.index(train[j]) < temp.index(train[j+1]):
            train[j], train[j+1] = train[j+1], train[j]
            time[j], time[j+1] = time[j+1], time[j]
            depart[j], depart[j+1] = depart[j+1], depart[j]
    if rc==0:
      break

sort3at1ce(train,time,depart)

for i in range(n):
  print(train[i],"will departure for",depart[i],"at",time[i],file=out)
  print(train[i],"will departure for",depart[i],"at",time[i])

out.close()