# -*- coding: utf-8 -*-
"""Task_1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2C41azQNXTCqsbNWC0ny8pBEft2ki1B

"""

inp= open('/content/input1a.txt','r')
out= open('output1b.txt','w')

lines= inp.readlines()
line1= (lines[0][0:-1]).split(" ")
n1= int(line1[0])
wsum = int(n[1])
arr= lines[1].split(" ")
for i in range(n1):
 arr[i]= int(arr[i]) 
dict1={}
flag=False

for i in range(n1):
  x=wsum-arr[i]   
  if x in  dict1:
      fst=dict1[x] 
      flag=True
      print(fst,i+1,file=out)
      print(fst,i+1)
      break  
  elif x not in dict1:
      dict1[arr[i]]=i+1

if flag==False:
  print('Impossible') 
  print('Impossible',file=out) 
out.close()