# -*- coding: utf-8 -*-
"""Task_1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2C41azQNXTCqsbNWC0ny8pBEft2ki1B

"""

file= open('/content/input1a.txt','r')
out = open('output1.txt','w')

lines = file.readlines()
x= lines[0].split(' ')
array= lines[1].split(' ')
for i in range(len(array)):
  y= int(array[i])
  array[i]=y

n= int(x[0])
wsum= int(x[1])
status= False

for i in range(n):
  for j in range(n):
    if i!=j and status == False:
      if int(array[i]) + int(array[j]) == wsum:
        #print(i+1,j+1)
        print(j+1,i+1,file=out)
        status= True
        break
if status== False:
  #print("Impossible")
  print("Impossible",file=out)

out.close()
