# -*- coding: utf-8 -*-
"""task_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSOtAjXkhV5R50ma-XwKcUgeBg4thR84#scrollTo=9hnbXr8UzGAp&uniqifier=3
"""
f = open('/content/input5a.txt','r')
out= open('output5.txt','w')
lines= f.readlines()
n= int(lines[0])
arr= lines[1].split(' ')
for i in range(len(arr)):
  x=int(arr[i])
  arr[i]=x

start=0
end=len(arr)-1


def Quicksort(arr, start, end):
  if start < end:
    pst = Partition(arr, start, end)
    Quicksort(arr, start, pst - 1)
    Quicksort(arr, pst + 1, end)
    Quicksort(arr, pst + 1, end)


def Partition(arr, start, end):
  pivot = arr[end]
  i = start - 1
  for j in range(start, end):
    if arr[j] < pivot:
      i = i + 1
      (arr[i], arr[j]) = (arr[j], arr[i])
  (arr[i + 1], arr[end]) = (arr[end], arr[i + 1])
  return i + 1

Quicksort(arr, start, end)
for i in arr:
  print(i,end=' ')
  print(i,end=' ',file=out)
out.close()