# -*- coding: utf-8 -*-
"""task_2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9D0mmTztd4C1_S-CROX9S9PaHPweHVE

#2(a)
"""

inp= open('/content/input2a.txt','r')
out= open('output2a.txt','w')
lines= inp.readlines()
n1= int(lines[0])
n2= int(lines[2][0:-1])

arr= lines[1].split(" ")
for i in range(n1):
 arr[i]= int(arr[i])

arr1= lines[3].split(" ")
for i in range(n2):
 arr1[i]= int(arr1[i])


arr.extend(arr1)
finalarr = sorted(arr)

for i in finalarr:
  print(i,end=" ")
  print(i,end=" ",file=out)

out.close()