# -*- coding: utf-8 -*-
"""task_2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9D0mmTztd4C1_S-CROX9S9PaHPweHVE
"""

file= open('/content/input2a.txt','r')
out= open('output2.txt','w')
lines= file.readlines()
n1= int(lines[0])
n2= int(lines[2])

left= lines[1].split(" ")
for i in range(n1):
 left[i]= int(left[i])

right= lines[3].split(" ")
for i in range(n2):
 right[i]= int(right[i])

farr= [0]*(n1+n2)
i,j,k=0,0,0

while i < len(left) and j < len(right):
  if left[i] <= right[j]:
    farr[k] = left[i]
    i += 1
  else:
    farr[k] = right[j]
    j += 1
  k += 1
while i < len(left):
  farr[k] = left[i]
  i += 1
  k += 1
while j < len(right):
  farr[k]=right[j]
  j += 1
  k += 1
for i in farr:
  print(i,end=" ")
  print(i,end=" ",file=out)

out.close()