# -*- coding: utf-8 -*-
"""task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TsALSIKLsr013m2qbe5cKozv3jQNEnDv

#1a
"""

f =open("/content/input1.txt",'r')
out1a= open("output1a.txt",'w')

arr=[]
n = f.readlines()
u= n[0].split(" ")
v=int(u[1].strip())
u= int(u[0])
graph=[]
for i in range(u+1): 
  g=[0]*(u+1)
  graph.append(g)

for i in range(len(n)-1):
  x=n[i+1]
  x=x.split(" ")
  a=int(x[0])
  b=int(x[1])
  c=int(x[2].strip())
  arr.append([a,b,c])
  
for i in arr:
  c=i[0]
  r=i[1]
  w=i[2]
  graph[c][r]=w

for i in graph:
  print(i)
  print(i,file=out1a)

out1a.close()

"""#1b"""

f =open("/content/input1.txt",'r')
out1b= open("output1b.txt",'w')

xs = [[]for i in range(0,len(graph)+1)]
for i in arr:
  idx=i[0]
  x=i[1]
  y=i[2]
  xs[idx+1].append((x,y))

for i in range(1,len(xs)):
  print(i-1,":",end="")
  print(i-1,":",end="",file=out1b)
  x=xs[i]
  for j in x:
    print(j,end=" ",file=out1b)
    print(j,end=" ")
  print()
  print(file=out1b)

out1b.close()
out1a.close()