# -*- coding: utf-8 -*-
"""task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGenykTn6sQ674pUjLXEb_4f0KMUDnSB
"""
file= open('/content/input4a.txt','r')
out= open('output4.txt','w')
lines= file.readlines()
line1= lines[0].strip().split(' ')
n,m = int(line1[0]), int(line1[1])

arr= [None]*n
for i in range(1,len(lines)):
  x= lines[i].strip().split(' ')
  a,b =x
  arr[i-1]=(int(a),int(b))

arr.sort(key=lambda x: x[1])
finarr = [0] *n
done = 0

for i in range(m):
  ltime= -1
  for j in range(n):
    if finarr[j]== 0 and arr[j][0]>=ltime:
      finarr[j]= 1
      ltime=arr[j][1]
      done +=1

#print(str(done))
print(str(done),file = out)